### ISSUE TITLE
Player 2 fire button dosnt work 

### ISSUE THREAD

**Issue by apison** [Chips-fr/uae4arm-libretro#4]
This is a very good improvement respect the old version, bur there is a bug with the fire button of the player 2, sometimes it dosnt work, . A fix will be very appreciated

**Comment by Chips-fr** [comment]
This repo is a copy of the branch libretro of https://github.com/Chips-fr/uae4arm-rpi
Note that the purpose of this version to supporte vita since it's the only one supporting vita. On which device you use it ?
For the 2nd joystick button issue, do you have a specific game to reproduce easily ?

**Comment by apison** [comment]
I use this versione with a custom linux board, it s the only version that run in fullspeed, I' ve also compiled uae4arm rpi but sadly it doesnt run in full speed on my board even if it hasnt the player 2 fire button bugs. I ve tested the problem with alien storm ,  sometimes fire works sometimes dont.  I ve tried to figure it out where the problem is but for now without success. What the difference between the uae4arm-libretro-new and this one?

**Comment by Chips-fr** [comment]
uae4arm-libretro-new should be close to master of uae4arm-rpi with some update missing. On raspberry both uae4arm-rpi and this one has very close performances. Strange that you doesn't feel the same but i haven't done so many test.
I tried 2nd player with this repo on bubble bobble, i feel like it was more difficult to maintain a constant rate of bubble with 2nd player than first...

**Comment by Chips-fr** [comment]
Try with followin inputdevice_vsync:

```
void inputdevice_vsync (void)
{
	static int back_joy0button=0;

	getjoystate (0, &joy1dir, &joy1button);
	getjoystate (1, &joy0dir, &joy0button);


	if (second_joystick_enable == 1)
	{
		back_joy0button= joy0button;
		buttonstate[0]= joy0button & 0x01;

	}
	else
	{
		if (joy0button!=back_joy0button)
  		{
			back_joy0button= joy0button;
			buttonstate[0]= joy0button & 0x01;
		}
	}
}
```
I don't really understand the original code but i think it relate only with mouse button and not joystick one...

**Comment by apison** [comment]
Thank you chips, your patch works correctly, now player 2 fire button always work.

**Comment by apison** [comment]
Another thing I've found, it seems that there is something wrong when Model is setted to Auto, it doesn't work properly for me, I've fixed it loading the preferences after parsing the cmdline.

I've simple added this line of code on line 483 of the file main.cpp, in the function real_main2 .

update_prefs_retrocfg(&currprefs);

If you have some time give it a try, the same problem seems to be present in the uae4arm-rpi.

**Comment by Chips-fr** [comment]
Good to know for the 2nd player, I will push the correction somedays...
Do you have any example of the problem you get in auto mode ?

**Comment by apison** [comment]
You can try with any aga games, auto mode is supposed to switch automatically to aga but it doesnt work.

**Comment by Chips-fr** [comment]
If "aga" is present in the file name of the selected "rom" it automatically switch to A1200 config. I tested this on both retroarch and emulation station frontend.
